### ISSUE TITLE
Upgrade dependency versions

### ISSUE THREAD

**Issue by a5anka** [wso2/wso2-httpcore-nio#37]
- [ ] mockito-core from 1.8.5 to 2.28.2 #36 
- [ ] jacoco-maven-plugin from 0.8.0 to 0.8.4 #35 
- [ ] mockito-core from 1.8.5 to 2.28.2 #34

**Comment by anupama-pathirage** [comment]
Closing as this is outdated now.
